export { default as SinglePageLayout } from './SinglePageLayout'
export { Navigation } from './Navigation'
export { HeroSection } from './HeroSection'
export { GallerySection } from './GallerySection'
export { ArtistSection } from './ArtistSection'
export { ExhibitionSection } from './ExhibitionSection'
export { ContactSection } from './ContactSection'
export { ArtworkModal } from './ArtworkModal'