// Backup simple fallback data with Number-based slugs
import type { Artwork } from '@/lib/types'
import { getOptimizedArtworkImagePath } from './optimized-image-utils'

export const fallbackArtworksData: Artwork[] = [
  {
    id: '1',
    slug: '01',
    title: '작품 01',
    year: 2025,
    medium: '화선지에 먹',
    dimensions: '70 x 140 cm',
    aspectRatio: '1/2',
    description: '전통 서예의 아름다움을 현대적 감각으로 재해석한 작품입니다.',
    imageUrl: getOptimizedArtworkImagePath('01', 'medium'),
    imageId: '01',
    imageUrlQuery: 'korean calligraphy modern traditional',
    artistNote: '전통과 현대의 조화를 추구한 작품입니다.',
    featured: true,
    category: 'recent',
    available: true,
    tags: ['전통', '현대', '조화'],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: '02',
    title: '작품 02',
    year: 2025,
    medium: '화선지에 먹',
    dimensions: '90 x 90 cm',
    aspectRatio: '1/1',
    description: '먹의 농담으로 표현한 내면의 깊이를 담은 작품입니다.',
    imageUrl: getOptimizedArtworkImagePath('02', 'medium'),
    imageId: '02',
    imageUrlQuery: 'ink depth inner emotion calligraphy',
    artistNote: '먹의 다양한 농도로 감정의 깊이를 표현했습니다.',
    featured: false,
    category: 'recent',
    available: true,
    tags: ['먹', '감정', '깊이'],
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: '3',
    slug: '03',
    title: '작품 03',
    year: 2025,
    medium: '화선지에 먹',
    dimensions: '70 x 100 cm',
    aspectRatio: '7/10',
    description: '여백의 미학을 통해 보여주는 공간의 깊이',
    imageUrl: getOptimizedArtworkImagePath('03', 'medium'),
    imageId: '03',
    imageUrlQuery: 'space depth aesthetic void calligraphy',
    artistNote: '여백을 통해 무한한 공간감을 표현하고자 했습니다.',
    featured: false,
    category: 'recent',
    available: true,
    tags: ['여백', '공간', '깊이'],
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  }
]