import type { Artwork, Artist } from '@/lib/types'

export const mockArtwork: Artwork = {
  id: '1',
  title: '작품 1',
  slug: 'artwork-1',
  year: 2024,
  medium: '한지에 먹',
  dimensions: '70 x 100 cm',
  aspectRatio: '3/4',
  description: '테스트용 작품 설명입니다.',
  imageUrl: '/images/artworks/2024/artwork-1.jpg',
  artistNote: '작가의 노트입니다.',
  technique: '서예',
  series: '테스트 시리즈',
  featured: false,
  tags: ['서예', '먹', '한지'],
  available: true,
  exhibition: undefined,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
}

export const mockArtworks: Artwork[] = [
  mockArtwork,
  {
    ...mockArtwork,
    id: '2',
    title: '먹, 그리고...',
    slug: 'way-dao',
    featured: true,
    medium: '한지에 먹, 색',
    dimensions: '50 x 70 cm',
    aspectRatio: '4/5',
    imageUrl: '/images/artworks/2024/way-dao.jpg',
  },
  {
    ...mockArtwork,
    id: '3',
    title: '복 福',
    slug: 'blessing-fu',
    year: 2023,
    medium: '선지에 먹',
    dimensions: '60 x 80 cm',
    aspectRatio: '3/4',
    imageUrl: '/images/artworks/2023/blessing-fu.jpg',
  },
  {
    ...mockArtwork,
    id: '4',
    title: '항다반 恒茶飯',
    slug: 'everyday-tea-rice',
    year: 2025,
    medium: '화선지에 먹',
    dimensions: '40 x 60 cm',
    aspectRatio: '2/3',
    featured: true,
    imageUrl: '/images/artworks/2025/everyday-tea-rice.jpg',
  },
]

export const mockArtworkWithoutOptionalFields: Artwork = {
  id: '5',
  title: '최소 작품',
  slug: 'minimal-artwork',
  year: 2024,
  medium: '한지에 먹',
  dimensions: '50 x 70 cm',
  aspectRatio: '1/1',
  description: '기본 작품',
  imageUrl: '/images/default.jpg',
}

export const mockArtist: Artist = {
  id: '1',
  name: '배옥영',
  bio: '한국의 현대 서예가로, 전통 서예와 현대적 감각을 결합한 독특한 작품 세계를 구축하고 있습니다.',
  statement: '서예는 단순한 글씨가 아닌, 마음과 정신을 표현하는 예술입니다.',
  profileImageUrl: '/Images/Artist/artist.png',
  birthYear: 1970,
  education: [
    '서울대학교 동양화과 졸업',
    '중국 베이징대학 서예과 석사',
  ],
  exhibitions: [
    '2024 개인전 - 갤러리 현대',
    '2023 그룹전 - 국립현대미술관',
    '2022 개인전 - 아람미술관',
  ],
  awards: [
    '2024 대한민국서예대전 대상',
    '2023 김정호서예상',
    '2022 전국서예공모전 금상',
  ],
  collections: [
    '국립현대미술관',
    '서울시립미술관',
    '부산시립미술관',
  ],
  website: 'https://anam-gallery.com',
  email: 'artist@anam-gallery.com',
  phone: '+82-10-1234-5678',
  socialLinks: {
    instagram: '@anam_artist',
    facebook: 'anam.artist',
    website: 'https://anam-gallery.com',
  },
  birthPlace: '서울, 대한민국',
  currentLocation: '서울, 대한민국',
  specialties: ['한글서예', '한문서예', '현대서예'],
  influences: ['김정희', '원교', '조맹부'],
  teachingExperience: [
    '서울대학교 미술대학 겸임교수 (2020-현재)',
    '홍익대학교 미술대학 강사 (2018-2020)',
  ],
  publications: [
    '현대서예의 이해 (2023)',
    '먹과 붓의 대화 (2021)',
  ],
  memberships: [
    '한국서예협회',
    '대한서예가협회',
    '현대서예연구회',
  ],
  philosophy: '서예는 마음을 닦고 정신을 수양하는 도구이며, 아름다운 글씨는 아름다운 마음에서 나옵니다.',
  techniques: ['해서', '행서', '초서', '전서', '예서'],
  materials: ['한지', '선지', '화선지', '먹', '붓'],
}
